# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import accounting_pb2 as accounting__pb2


class DNSServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Resolve = channel.unary_unary(
        '/api.DNSService/Resolve',
        request_serializer=accounting__pb2.DNSRequest.SerializeToString,
        response_deserializer=accounting__pb2.DNSResponse.FromString,
        )


class DNSServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Resolve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DNSServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Resolve': grpc.unary_unary_rpc_method_handler(
          servicer.Resolve,
          request_deserializer=accounting__pb2.DNSRequest.FromString,
          response_serializer=accounting__pb2.DNSResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.DNSService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
