# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import events_pb2 as events__pb2


class EventsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/api.EventsService/Send',
        request_serializer=events__pb2.SendRequest.SerializeToString,
        response_deserializer=events__pb2.SendResponse.FromString,
        )
    self.Receive = channel.unary_unary(
        '/api.EventsService/Receive',
        request_serializer=events__pb2.ReceiveRequest.SerializeToString,
        response_deserializer=events__pb2.ReceiveResponse.FromString,
        )
    self.Confirm = channel.unary_unary(
        '/api.EventsService/Confirm',
        request_serializer=events__pb2.ConfirmRequest.SerializeToString,
        response_deserializer=events__pb2.ConfirmResponse.FromString,
        )


class EventsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Receive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Confirm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=events__pb2.SendRequest.FromString,
          response_serializer=events__pb2.SendResponse.SerializeToString,
      ),
      'Receive': grpc.unary_unary_rpc_method_handler(
          servicer.Receive,
          request_deserializer=events__pb2.ReceiveRequest.FromString,
          response_serializer=events__pb2.ReceiveResponse.SerializeToString,
      ),
      'Confirm': grpc.unary_unary_rpc_method_handler(
          servicer.Confirm,
          request_deserializer=events__pb2.ConfirmRequest.FromString,
          response_serializer=events__pb2.ConfirmResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.EventsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
