# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='api',
  syntax='proto3',
  serialized_options=_b('\n\022com.northghost.apiB\013ProtoEvents'),
  serialized_pb=_b('\n\x0c\x65vents.proto\x12\x03\x61pi\"M\n\x0bSendMessage\x12\x10\n\x08\x64\x65\x64up_id\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\x0c\"?\n\x0bSendRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12!\n\x07message\x18\x02 \x01(\x0b\x32\x10.api.SendMessage\"\x0e\n\x0cSendResponse\"I\n\x0eReceiveRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x14\n\x0clock_seconds\x18\x03 \x01(\x03\"@\n\x0eReceiveMessage\x12\x12\n\nconfirm_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"8\n\x0fReceiveResponse\x12%\n\x08messages\x18\x01 \x03(\x0b\x32\x13.api.ReceiveMessage\"3\n\x0e\x43onfirmRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nconfirm_id\x18\x02 \x01(\t\"\x11\n\x0f\x43onfirmResponse2\xae\x01\n\rEventsService\x12-\n\x04Send\x12\x10.api.SendRequest\x1a\x11.api.SendResponse\"\x00\x12\x36\n\x07Receive\x12\x13.api.ReceiveRequest\x1a\x14.api.ReceiveResponse\"\x00\x12\x36\n\x07\x43onfirm\x12\x13.api.ConfirmRequest\x1a\x14.api.ConfirmResponse\"\x00\x42!\n\x12\x63om.northghost.apiB\x0bProtoEventsb\x06proto3')
)




_SENDMESSAGE = _descriptor.Descriptor(
  name='SendMessage',
  full_name='api.SendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dedup_id', full_name='api.SendMessage.dedup_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='api.SendMessage.group_id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='api.SendMessage.type', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='api.SendMessage.body', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=98,
)


_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='api.SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue', full_name='api.SendRequest.queue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='api.SendRequest.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=163,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='api.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=179,
)


_RECEIVEREQUEST = _descriptor.Descriptor(
  name='ReceiveRequest',
  full_name='api.ReceiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue', full_name='api.ReceiveRequest.queue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='api.ReceiveRequest.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lock_seconds', full_name='api.ReceiveRequest.lock_seconds', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=254,
)


_RECEIVEMESSAGE = _descriptor.Descriptor(
  name='ReceiveMessage',
  full_name='api.ReceiveMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm_id', full_name='api.ReceiveMessage.confirm_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='api.ReceiveMessage.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='api.ReceiveMessage.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=320,
)


_RECEIVERESPONSE = _descriptor.Descriptor(
  name='ReceiveResponse',
  full_name='api.ReceiveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='api.ReceiveResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=378,
)


_CONFIRMREQUEST = _descriptor.Descriptor(
  name='ConfirmRequest',
  full_name='api.ConfirmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue', full_name='api.ConfirmRequest.queue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confirm_id', full_name='api.ConfirmRequest.confirm_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=431,
)


_CONFIRMRESPONSE = _descriptor.Descriptor(
  name='ConfirmResponse',
  full_name='api.ConfirmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=450,
)

_SENDREQUEST.fields_by_name['message'].message_type = _SENDMESSAGE
_RECEIVERESPONSE.fields_by_name['messages'].message_type = _RECEIVEMESSAGE
DESCRIPTOR.message_types_by_name['SendMessage'] = _SENDMESSAGE
DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.message_types_by_name['ReceiveRequest'] = _RECEIVEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveMessage'] = _RECEIVEMESSAGE
DESCRIPTOR.message_types_by_name['ReceiveResponse'] = _RECEIVERESPONSE
DESCRIPTOR.message_types_by_name['ConfirmRequest'] = _CONFIRMREQUEST
DESCRIPTOR.message_types_by_name['ConfirmResponse'] = _CONFIRMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMessage = _reflection.GeneratedProtocolMessageType('SendMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.SendMessage)
  ))
_sym_db.RegisterMessage(SendMessage)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDREQUEST,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.SendRequest)
  ))
_sym_db.RegisterMessage(SendRequest)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)

ReceiveRequest = _reflection.GeneratedProtocolMessageType('ReceiveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEREQUEST,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.ReceiveRequest)
  ))
_sym_db.RegisterMessage(ReceiveRequest)

ReceiveMessage = _reflection.GeneratedProtocolMessageType('ReceiveMessage', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEMESSAGE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.ReceiveMessage)
  ))
_sym_db.RegisterMessage(ReceiveMessage)

ReceiveResponse = _reflection.GeneratedProtocolMessageType('ReceiveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVERESPONSE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.ReceiveResponse)
  ))
_sym_db.RegisterMessage(ReceiveResponse)

ConfirmRequest = _reflection.GeneratedProtocolMessageType('ConfirmRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMREQUEST,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.ConfirmRequest)
  ))
_sym_db.RegisterMessage(ConfirmRequest)

ConfirmResponse = _reflection.GeneratedProtocolMessageType('ConfirmResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMRESPONSE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:api.ConfirmResponse)
  ))
_sym_db.RegisterMessage(ConfirmResponse)


DESCRIPTOR._options = None

_EVENTSSERVICE = _descriptor.ServiceDescriptor(
  name='EventsService',
  full_name='api.EventsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=453,
  serialized_end=627,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='api.EventsService.Send',
    index=0,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Receive',
    full_name='api.EventsService.Receive',
    index=1,
    containing_service=None,
    input_type=_RECEIVEREQUEST,
    output_type=_RECEIVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Confirm',
    full_name='api.EventsService.Confirm',
    index=2,
    containing_service=None,
    input_type=_CONFIRMREQUEST,
    output_type=_CONFIRMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSSERVICE)

DESCRIPTOR.services_by_name['EventsService'] = _EVENTSSERVICE

# @@protoc_insertion_point(module_scope)
