# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vpnserver_label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vpnserver_label.proto',
  package='api',
  syntax='proto3',
  serialized_options=_b('\n\022com.northghost.apiB\023ProtoVpnserverLabel'),
  serialized_pb=_b('\n\x15vpnserver_label.proto\x12\x03\x61pi\",\n\x0eVpnServerLabel\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB)\n\x12\x63om.northghost.apiB\x13ProtoVpnserverLabelb\x06proto3')
)




_VPNSERVERLABEL = _descriptor.Descriptor(
  name='VpnServerLabel',
  full_name='api.VpnServerLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='api.VpnServerLabel.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.VpnServerLabel.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['VpnServerLabel'] = _VPNSERVERLABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VpnServerLabel = _reflection.GeneratedProtocolMessageType('VpnServerLabel', (_message.Message,), dict(
  DESCRIPTOR = _VPNSERVERLABEL,
  __module__ = 'vpnserver_label_pb2'
  # @@protoc_insertion_point(class_scope:api.VpnServerLabel)
  ))
_sym_db.RegisterMessage(VpnServerLabel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
