# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vpnserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vpnserver_label_pb2 as vpnserver__label__pb2
import vpnserver_output_pb2 as vpnserver__output__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vpnserver.proto',
  package='api',
  syntax='proto3',
  serialized_options=_b('\n\022com.northghost.apiB\016ProtoVpnserver'),
  serialized_pb=_b('\n\x0fvpnserver.proto\x12\x03\x61pi\x1a\x15vpnserver_label.proto\x1a\x16vpnserver_output.proto\"\xbd\x01\n\tVpnServer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12#\n\x06labels\x18\x04 \x03(\x0b\x32\x13.api.VpnServerLabel\x12\x10\n\x08priority\x18\x05 \x01(\x03\x12\x10\n\x08sessions\x18\x06 \x01(\x03\x12\x11\n\tprotocols\x18\x07 \x03(\t\x12%\n\x07outputs\x18\x08 \x03(\x0b\x32\x14.api.VpnServerOutputB$\n\x12\x63om.northghost.apiB\x0eProtoVpnserverb\x06proto3')
  ,
  dependencies=[vpnserver__label__pb2.DESCRIPTOR,vpnserver__output__pb2.DESCRIPTOR,])




_VPNSERVER = _descriptor.Descriptor(
  name='VpnServer',
  full_name='api.VpnServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.VpnServer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='api.VpnServer.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active', full_name='api.VpnServer.active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='api.VpnServer.labels', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='api.VpnServer.priority', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessions', full_name='api.VpnServer.sessions', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocols', full_name='api.VpnServer.protocols', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='api.VpnServer.outputs', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=261,
)

_VPNSERVER.fields_by_name['labels'].message_type = vpnserver__label__pb2._VPNSERVERLABEL
_VPNSERVER.fields_by_name['outputs'].message_type = vpnserver__output__pb2._VPNSERVEROUTPUT
DESCRIPTOR.message_types_by_name['VpnServer'] = _VPNSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VpnServer = _reflection.GeneratedProtocolMessageType('VpnServer', (_message.Message,), dict(
  DESCRIPTOR = _VPNSERVER,
  __module__ = 'vpnserver_pb2'
  # @@protoc_insertion_point(class_scope:api.VpnServer)
  ))
_sym_db.RegisterMessage(VpnServer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
