# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vpnserver_output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vpnserver_label_pb2 as vpnserver__label__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vpnserver_output.proto',
  package='api',
  syntax='proto3',
  serialized_options=_b('\n\022com.northghost.apiB\024ProtoVpnserverOutput'),
  serialized_pb=_b('\n\x16vpnserver_output.proto\x12\x03\x61pi\x1a\x15vpnserver_label.proto\"6\n\x0fVpnServerOutput\x12#\n\x06labels\x18\x01 \x03(\x0b\x32\x13.api.VpnServerLabelB*\n\x12\x63om.northghost.apiB\x14ProtoVpnserverOutputb\x06proto3')
  ,
  dependencies=[vpnserver__label__pb2.DESCRIPTOR,])




_VPNSERVEROUTPUT = _descriptor.Descriptor(
  name='VpnServerOutput',
  full_name='api.VpnServerOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='api.VpnServerOutput.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=108,
)

_VPNSERVEROUTPUT.fields_by_name['labels'].message_type = vpnserver__label__pb2._VPNSERVERLABEL
DESCRIPTOR.message_types_by_name['VpnServerOutput'] = _VPNSERVEROUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VpnServerOutput = _reflection.GeneratedProtocolMessageType('VpnServerOutput', (_message.Message,), dict(
  DESCRIPTOR = _VPNSERVEROUTPUT,
  __module__ = 'vpnserver_output_pb2'
  # @@protoc_insertion_point(class_scope:api.VpnServerOutput)
  ))
_sym_db.RegisterMessage(VpnServerOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
